api_platform:
    # Specify a path name generator to use.
    path_segment_name_generator: 'api_platform.path_segment_name_generator.dash'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        pagination:
            # The default name of the parameter handling the page number.
            page_parameter_name: 'toto'
    defaults:
        pagination_items_per_page: 10

