/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnimalBreed } from './animal-breed';


export interface Animal { 
    readonly id?: number;
    name: string;
    owner?: string | null;
    gender?: string | null;
    breeds?: Array<AnimalBreed>;
}

