/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OwnerJsonldFullOwner { 
    readonly '@context?': string | any | null;
    readonly '@id'?: string;
    readonly '@type'?: string;
    readonly id?: number;
    firstName: string;
    lastName: string;
    birthAt?: string | null;
    animals?: Array<string>;
}

